---
- name: add  multiple users
  hosts: all
  become: true
  tasks: 
    - name: add users
      user: name='{{ item }}' state=present
      with_items:  
         - basha
         - kumar
         - tushar   
