---
- name: httpd error handling
  hosts: all
  become: true
  tasks:
    - name: httpd package installing
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"    
    - name: httpd package service starting
      service:
        name: httpd---
        state: started
      when: ansible_os_family == "RedHat"  
      ignore_errors: yes
      when: ansible_os_family == "RedHat"    
    - name: apache2 package installing
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"    
    - name: apache2 package service starting
      community.general.apache2_module:
        state: present
      when: ansible_os_family == "Debian" 
