---
- name: installing tomcat app
  hosts: all
  become: true
  tasks: 
     - name: installing java in redhat
       yum:
         name: java
         state: installed
       when: ansible_os_family == "RedHat"
     - name: installing java in redhat
       apt:
         name: default-jdk
         state: present
       when: ansible_os_family == "Debian"
     - name: downloading url
       get_url:
         url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz
         dest: /opt
     - name: extracting tomcat file
       ansible.builtin.unarchive:
         src: /opt/apache-tomcat-8.5.96.tar.gz
         dest: /opt
         remote_src: yes
     - name: changing file permissions
       file:
         path: /opt/apache-tomcat-8.5.96/bin/startup.sh
         mode: 0777
     - name: start tomcat service
       shell: nohup ./startup.sh
       args: 
         chdir: /opt/apache-tomcat-8.5.96/bin

     

