---
- name: unsinstalling httpd
  hosts: all
  become: true
  tasks:

  - name: unsintall httpd
    service:
           name: httpd
           state: stopped
  - name: uninstall httpd
    yum:
        name: httpd
        state: absent  

