---
# tasks file for setup_apache_role

- name: install httpd
  yum:
        name: httpd
        state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd service
- name: install apache
  apt:
        name: apache2
        state: present
  when: ansible_os_family == "Debion"
  notify: start apache service  
- name: copy index.html
  copy:
        src: /home/ansadmin/index.html
        dest: /var/www/ansadmin
        mode: 0666 


